import type { Metadata } from "next";
import { PT_Serif, Cabin } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import { UserProvider } from '@auth0/nextjs-auth0/client';

const ptSerif = PT_Serif({
  subsets: ['latin'],
  weight: "400",
  variable: '--font-PT-serif'
});
const cabin = Cabin({
  subsets: ["latin"], weight: "400",
  variable: '--font-Cabin'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={` ${ptSerif.className} ${cabin.variable} ${ptSerif.variable}`}>
          <Header />
          <div className="flex-1 flex  flex-col overflow-hidden">
            {children}
          </div>
        </body>
      </UserProvider>
    </html >
  );
}
